#!/usr/bin/env bash

set -euo pipefail

usage() {
	cat <<-USAGE
		nix-freeze 0.1.0

		Save Nix environment as a Cabal constraints file.
		Only usable inside a Nix shell.

		Example:

		  nix-freeze > cabal.config
	USAGE

	exit 1
}

env_check() {
	[ -n "${NIX_GHCPKG:-}" ] || usage
}

main() {
	env_check

	declare name version

	echo "constraints:"

	"$NIX_GHCPKG" list | while read -r; do
		if [[ $REPLY =~ [[:space:]]+(([^0-9\([:space:]][^-]*-?)+)-([0-9.]+) ]]; then
			name=${BASH_REMATCH[1]}
			version=${BASH_REMATCH[3]}

			echo "  ${name} ==${version},"
		fi
	done

	# A constraint that is always true. Once Cabal learns to ignore trailing
	# commas, this can be removed.
	echo "  base installed"
}

main "$@"
